# Generated by Django 2.0.13 on 2019-05-16 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lend_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lend_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Lend_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Book_info')),
                ('Lend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Return_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Return_lend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Lend_info')),
            ],
        ),
        migrations.CreateModel(
            name='Review_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_score', models.PositiveIntegerField(choices=[(1, 'おすすめしない'), (2, 'あまりおすすめしない'), (3, 'どちらでもない'), (4, 'おすすめする'), (5, '強くおすすめする')])),
            ],
        ),
        migrations.CreateModel(
            name='Title_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_name', models.CharField(max_length=50)),
                ('Title_ISBN', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='review_info',
            name='Review_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Title_info'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='Book_ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Title_info'),
        ),
    ]
